# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            io.js 한국 커뮤니티
tagline:          'io.js 한글화'
description:      '<a href="https://iojs.org" target="_blank">io.js</a> 관련 소식, 정보, 글 등을 한국어로 번역해서 공유합니다.'
url:              http://iojs.github.io/iojs-kr
baseurl:          /iojs-kr

author:
  name:           'io.js 한국어 번역팀'
  url:            https://github.com/iojs/iojs-kr

paginate:         5

github:
  repo:           https://github.com/iojs/iojs-kr
