name: Deploy on master
on:
  push:
    branches:
      - master
jobs:
  buildAndDeploy:
    name: build & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run generate
      - run: ./bin/generate_rsa
        env:
          ID_RSA: ${{ secrets.ID_RSA }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      - run: npm run publish
